### ISSUE TITLE
cloning bitbucket repos fail

### ISSUE THREAD

**Issue by uffejakobsen** [felipec/git-remote-hg#41] opened 2015-05-03 00:05 UTC
Hi,

cloning bitbucket repos all seems to fail like this

git clone hg::https://bitbucket.org/pytest-dev/pytest aa.git

Cloning into 'aa.git'...
Traceback (most recent call last):
  File "/sbin/git-remote-hg", line 1307, in <module>
    sys.exit(main(sys.argv))
  File "/sbin/git-remote-hg", line 1271, in main
    repo = get_repo(url, alias)
  File "/sbin/git-remote-hg", line 429, in get_repo
    repo.pull(peer, heads=None, force=True)
  File "/usr/lib/python2.7/site-packages/mercurial/repoview.py", line 311, in __getattr__
    return getattr(self._unfilteredrepo, attr)
AttributeError: 'localrepository' object has no attribute 'pull'

Archlinux
git version 2.3.7
git-remote-hg version 0.2-2
mercirual (3.3.x and 3.4)

**Comment by jmccrohan** [comment] 2015-05-04 16:39
Hi @uffejakobsen,

Are you using Debian Unstable? This looks to be identical to Debian Bug [#784209](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784209) which was reported earlier today.

This bug is ultimately due to Mercurial 3.4 being uploaded to Unstable recently, and triggering Issue #28.

I plan to upload a new version of git-remote-hg to Unstable soon which resolves this issue.

Cheers,
Jon

**Comment by uffejakobsen** [comment] 2015-05-04 21:11
Hi,

No - I'm running ArchLinux

The mercurial package for ArchLinux was just today updated  from 3.3.x to 3.4
That did not change anything - same problem

I've tried to implement the fix described in #28 - but is does not work - same problem

Kind regards Uffe

**Comment by benoit-pierre** [comment] 2015-05-04 21:40
You need the fix for #27 too. Try [fingolfin branch](https://github.com/fingolfin/git-remote-hg).

**Comment by uffejakobsen** [comment] 2015-05-05 21:02
Thanks - the fingolfin repo worked
What is the story ? is this repo not maintained anymore ?

**Comment by fingolfin** [comment] 2015-06-08 07:55
Judging by the lack of activity of Felipe, the owner of this repository, I think it is fair to say it is not maintained anymore -- or at least for the time being (he may of course return to work on it anyday). In the meantime, a partial solution is indeed to use my fork, which has a few patches and fixes -- but even with that, there is at least one remaining test failure when using Mercurial 3.4 (or was it 3.3? I forgot), due to some recent deeper changes in Mercurial (something related to phases -- anyway, it hopefully won't affect anybody, but I just wanted to point out that my fork is not "perfect" either).

**Comment by julianpistorius** [comment] 2015-07-03 18:10
I have the same issue:

Mac OS X: 10.9.5
Git: 2.4.0
Mercurial: 3.4

The branch from @fingolfin worked for me.

**Comment by fingolfin** [comment] 2015-12-04 09:54
@uffejakobsen Please consider closing this issue. It is a duplicate of #27

**Comment by chrisco314** [comment] 2015-12-08 18:45
I too, am using a mac, and experienced this problem when trying to check out hg as given in the README.md.  The fixes to the @fingolfin branch also fixed the problem for me (thanks), I hope it can be integrated soon.

Mac OS X: 10.11.1
Git: 2.5.1
Mercurial: 3.6.1

**Comment by felipec** [comment] 2016-05-17 04:03
Duplicate of issue #27.

**Closed by felipec** 2016-05-17 04:03 UTC
Labels: duplicate
