### ISSUE TITLE
Cloning: 'localrepository' object has no attribute 'pull'

### ISSUE THREAD

**Issue by pheerai** [felipec/git-remote-hg#45] opened 2015-07-06 09:24 UTC
Cloning remote repositories fails with the following output:

```bash
[oliver@oliver:git]$ git clone "hg::http://hg.gajim.org/gajim" gajim 
Cloning into 'gajim'...
Traceback (most recent call last):
  File "/usr/local/bin/git-remote-hg", line 1322, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/git-remote-hg", line 1286, in main
    repo = get_repo(url, alias)
  File "/usr/local/bin/git-remote-hg", line 433, in get_repo
    repo.pull(peer, heads=None, force=True)
  File "/usr/lib/python2.7/site-packages/mercurial/repoview.py", line 335, in __getattr__
    return getattr(self._unfilteredrepo, attr)
AttributeError: 'localrepository' object has no attribute 'pull'
```

**Comment by benoit-pierre** [comment] 2015-07-06 10:01
Duplicate of #27/#41.

Try fingolfin fork: https://github.com/fingolfin/git-remote-hg

**Comment by fingolfin** [comment] 2015-12-04 09:53
@pheerai Please reply, and either close this issue, or update with more information.

**Closed** 2015-12-04 09:54 UTC
